import { MigrationInterface, QueryRunner } from "typeorm";

export class AddPaymentTable1751090461925 implements MigrationInterface {
    name = 'AddPaymentTable1751090461925'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_178199805b901ccd220ab7740ec"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_17022daf3f885f7d35423e9971e"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_87b8888186ca9769c960e926870"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_b23c65e50a758245a33ee35fda1"`);
        await queryRunner.query(`ALTER TABLE "user_categories" DROP CONSTRAINT "FK_45435150cf9c026d714c9d847e6"`);
        await queryRunner.query(`ALTER TABLE "user_categories" DROP CONSTRAINT "FK_78d822ee1ebeb703dbecdf8e616"`);
        await queryRunner.query(`CREATE TYPE "public"."payment_status_enum" AS ENUM('SUCCESS', 'FAILED', 'REFUNDED', 'HOLDING')`);
        await queryRunner.query(`CREATE TYPE "public"."payment_method_enum" AS ENUM('BANK_TRANSFER', 'CREDIT_CARD', 'MOMO', 'ZALOPAY', 'VNPAY', 'PAYPAL', 'CASH', 'SEPAY')`);
        await queryRunner.query(`CREATE TABLE "payment" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "amount" bigint NOT NULL, "currency" character varying(3) NOT NULL DEFAULT 'VND', "status" "public"."payment_status_enum" NOT NULL, "method" "public"."payment_method_enum" NOT NULL, "transactionId" character varying(255) NOT NULL, "description" text, "metadata" json, "userId" integer NOT NULL, "talentId" integer NOT NULL, CONSTRAINT "PK_fcaec7df5adf9cac408c686b2ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN IF EXISTS "paymentStatus"`);
        await queryRunner.query(`ALTER TABLE "videos" ADD "thumbnailLink" character varying`);
        await queryRunner.query(`ALTER TABLE "videos" ADD "price" integer`);
        await queryRunner.query(`ALTER TABLE "categories" DROP CONSTRAINT "UQ_420d9f679d41281f282f5bc7d09"`);
        await queryRunner.query(`ALTER TABLE "categories" ALTER COLUMN "thumbnail" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "comments" ALTER COLUMN "star" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "comments" ALTER COLUMN "createdAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "comments" ALTER COLUMN "updatedAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "videos" ALTER COLUMN "hide_video" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "videos"."hide_video" IS NULL`);
        await queryRunner.query(`ALTER TABLE "videos" ALTER COLUMN "hide_video" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_151b79a83ba240b0cb31b2302d1"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "type"`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "type" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "email" character varying(255)`);
        await queryRunner.query(`COMMENT ON COLUMN "orders"."video_protocol_method" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "orders"."recipient" IS NULL`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "for_gender"`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "for_gender" character varying(20) NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."orders_status_enum" RENAME TO "orders_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."orders_status_enum" AS ENUM('pending', 'cancelled', 'paid', 'processing', 'sent_video', 'completed', 'complaint', 'resolving', 'refunded', 'rejected')`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "status" TYPE "public"."orders_status_enum" USING "status"::"text"::"public"."orders_status_enum"`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "status" SET DEFAULT 'pending'`);
        await queryRunner.query(`DROP TYPE "public"."orders_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "price"`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "price" numeric(10,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "paymentMethod"`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "paymentMethod" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "request_details"`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "request_details" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "example_video_link"`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "example_video_link" character varying(500)`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "video_from"`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "video_from" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "video_from_gender"`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "video_from_gender" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "hide_video_from" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "orders"."hide_video_from" IS NULL`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "video_link"`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "video_link" character varying(500)`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "userId" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "createdAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "updatedAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "UQ_8e1f623798118e629b46a9e6299"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "phone"`);
        await queryRunner.query(`ALTER TABLE "user" ADD "phone" character varying`);
        await queryRunner.query(`CREATE INDEX "IDX_178199805b901ccd220ab7740e" ON "role_permissions" ("role_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_17022daf3f885f7d35423e9971" ON "role_permissions" ("permission_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_87b8888186ca9769c960e92687" ON "user_roles" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_b23c65e50a758245a33ee35fda" ON "user_roles" ("role_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_45435150cf9c026d714c9d847e" ON "user_categories" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_78d822ee1ebeb703dbecdf8e61" ON "user_categories" ("category_id") `);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_151b79a83ba240b0cb31b2302d1" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment" ADD CONSTRAINT "FK_b046318e0b341a7f72110b75857" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment" ADD CONSTRAINT "FK_6dc957573d80b08119004232bf1" FOREIGN KEY ("talentId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_178199805b901ccd220ab7740ec" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_17022daf3f885f7d35423e9971e" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_87b8888186ca9769c960e926870" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_b23c65e50a758245a33ee35fda1" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_categories" ADD CONSTRAINT "FK_45435150cf9c026d714c9d847e6" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_categories" ADD CONSTRAINT "FK_78d822ee1ebeb703dbecdf8e616" FOREIGN KEY ("category_id") REFERENCES "categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user_categories" DROP CONSTRAINT "FK_78d822ee1ebeb703dbecdf8e616"`);
        await queryRunner.query(`ALTER TABLE "user_categories" DROP CONSTRAINT "FK_45435150cf9c026d714c9d847e6"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_b23c65e50a758245a33ee35fda1"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_87b8888186ca9769c960e926870"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_17022daf3f885f7d35423e9971e"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_178199805b901ccd220ab7740ec"`);
        await queryRunner.query(`ALTER TABLE "payment" DROP CONSTRAINT "FK_6dc957573d80b08119004232bf1"`);
        await queryRunner.query(`ALTER TABLE "payment" DROP CONSTRAINT "FK_b046318e0b341a7f72110b75857"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_151b79a83ba240b0cb31b2302d1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_78d822ee1ebeb703dbecdf8e61"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_45435150cf9c026d714c9d847e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b23c65e50a758245a33ee35fda"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_87b8888186ca9769c960e92687"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_17022daf3f885f7d35423e9971"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_178199805b901ccd220ab7740e"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "phone"`);
        await queryRunner.query(`ALTER TABLE "user" ADD "phone" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "UQ_8e1f623798118e629b46a9e6299" UNIQUE ("phone")`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "userId" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "video_link"`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "video_link" character varying NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "orders"."hide_video_from" IS 'Hide the video from?'`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "hide_video_from" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "video_from_gender"`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "video_from_gender" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "video_from"`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "video_from" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "example_video_link"`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "example_video_link" character varying`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "request_details"`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "request_details" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "paymentMethod"`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "paymentMethod" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "price"`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "price" integer NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."orders_status_enum_old" AS ENUM('pending', 'processing', 'completed', 'complaint', 'resolving', 'refunded', 'rejected')`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "status" TYPE "public"."orders_status_enum_old" USING "status"::"text"::"public"."orders_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "status" SET DEFAULT 'pending'`);
        await queryRunner.query(`DROP TYPE "public"."orders_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."orders_status_enum_old" RENAME TO "orders_status_enum"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "for_gender"`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "for_gender" character varying NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "orders"."recipient" IS 'Who is the video for?'`);
        await queryRunner.query(`COMMENT ON COLUMN "orders"."video_protocol_method" IS 'Phương thức giao video'`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "email" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "type"`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "type" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_151b79a83ba240b0cb31b2302d1" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "videos" ALTER COLUMN "hide_video" SET DEFAULT false`);
        await queryRunner.query(`COMMENT ON COLUMN "videos"."hide_video" IS 'Hide the video from?'`);
        await queryRunner.query(`ALTER TABLE "videos" ALTER COLUMN "hide_video" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "comments" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "comments" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "comments" ALTER COLUMN "star" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "categories" ALTER COLUMN "thumbnail" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "categories" ADD CONSTRAINT "UQ_420d9f679d41281f282f5bc7d09" UNIQUE ("slug")`);
        await queryRunner.query(`ALTER TABLE "videos" DROP COLUMN "price"`);
        await queryRunner.query(`ALTER TABLE "videos" DROP COLUMN "thumbnailLink"`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "paymentStatus" character varying NOT NULL`);
        await queryRunner.query(`DROP TABLE "payment"`);
        await queryRunner.query(`DROP TYPE "public"."payment_method_enum"`);
        await queryRunner.query(`DROP TYPE "public"."payment_status_enum"`);
        await queryRunner.query(`ALTER TABLE "user_categories" ADD CONSTRAINT "FK_78d822ee1ebeb703dbecdf8e616" FOREIGN KEY ("category_id") REFERENCES "categories"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_categories" ADD CONSTRAINT "FK_45435150cf9c026d714c9d847e6" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_b23c65e50a758245a33ee35fda1" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_87b8888186ca9769c960e926870" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_17022daf3f885f7d35423e9971e" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_178199805b901ccd220ab7740ec" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
