import { Category } from '@/modules/categories/entities/category.entity';
import { Role } from '@/modules/roles/entities/role.entity';
import { CreateTalentDto } from '@/modules/talents/dto/create-talent.dto';
import { User } from '@/modules/users/user.entity';
import { DataSource, In } from 'typeorm';

export const seedTalents = async (dataSource: DataSource) => {
  const talentRepository = dataSource.getRepository(User);
  const categoryRepository = dataSource.getRepository(Category);
  const roleRepository = dataSource.getRepository(Role);
  const talents: CreateTalentDto[] = [
    {
      name: 'Alyssa Edwards',
      nick_name: 'Alyssa',
      job: "TV Star - RuPaul's Drag Race",
      price: 15000,
      availableFor24hDelivery: true,
      email: 'alyssa01@example.com',
      description: 'One-of-a-kind video for your special moments',
      password: 'password123',
      tags: ['Promotional', 'For teens', 'US Talent'],
      categories: [2],
      avatar: 'https://www.cameo.com/cdn-cgi/image/fit=cover,format=auto,width=300,height=360/https://cdn.cameo.com/resizer/ameozFf-Z_avatar-1677196331157.jpg',
    },
    {
      name: 'James Murray',
      nick_name: 'James',
      job: 'TruTV - Impractical Jokers',
      price: 24900,
      availableFor24hDelivery: true,
      email: 'therealmurr@example.com',
      description: 'One-of-a-kind video for your special moments',
      password: 'password123',
      tags: ['Worth every penny', 'Roast your ex', '$300 or under'],
      categories: [4],
      avatar: 'https://www.cameo.com/cdn-cgi/image/fit=cover,format=auto,width=300,height=360/https://cdn.cameo.com/resizer/dDURo5LfcL_avatar-1720408367449.jpg',
    },
    {
      name: 'Jax Taylor',
      nick_name: 'Jax',
      job: 'Bravo -Vanderpump Rules, The Valley',
      price: 15800,
      availableFor24hDelivery: true,
      email: 'mrjaxtaylor@example.com',
      description: 'One-of-a-kind video for your special moments',
      password: 'password123',
      tags: ['Send a DM', 'Promotional', "Valentine's Day Stars"],
      categories: [1],
      avatar: 'https://www.cameo.com/cdn-cgi/image/fit=cover,format=auto,width=300,height=360/https://cdn.cameo.com/resizer/yKefDgZr-C_b981e007-c042-4f40-85cd-28d6b7b1d828.jpeg',
    },
    {
      name: 'Sonja Morgan',
      nick_name: 'Sonja',
      job: 'Bravo TV - Real Housewives of NYC',
      price: 9900,
      availableFor24hDelivery: true,
      email: 'sonjatmorgan@example.com',
      description: 'One-of-a-kind video for your special moments',
      password: 'password123',
      tags: ['Zoom Calls', 'Promotional', "Galentine's Day Pep Talk"],
      categories: [2],
      avatar: 'https://www.cameo.com/cdn-cgi/image/fit=cover,format=auto,width=300,height=360/https://cdn.cameo.com/resizer/eXQXkiubR_avatar-1689996772687.jpg',
    },
    {
      name: 'Les Gold',
      nick_name: 'Les',
      job: 'truTV - Hardcore Pawn',
      price: 4000,
      availableFor24hDelivery: true,
      email: 'lesg@example.com',
      description: 'One-of-a-kind video for your special moments',
      password: 'password123',
      tags: ['Send a DM', 'Promotional', 'US Talent'],
      categories: [2],
      avatar: 'https://www.cameo.com/cdn-cgi/image/fit=cover,format=auto,width=300,height=360/https://cdn.cameo.com/resizer/ameozFf-Z_avatar-1677196331157.jpg',
    },
    {
      name: 'Richard Blais',
      nick_name: 'Richard',
      job: 'The guy from that food show ',
      price: 4900,
      availableFor24hDelivery: true,
      email: 'richardblais@example.com',
      description: 'One-of-a-kind video for your special moments',
      password: 'password123',
      tags: ['Featured in Paid DM', 'Send a DM', 'Stars supporting GLAAD'],
      categories: [6],
      avatar: 'https://www.cameo.com/cdn-cgi/image/fit=cover,format=auto,width=300,height=360/https://cdn.cameo.com/resizer/D2t06hxBh_avatar-xoY4jZyYj.jpg',
    },
    {
      name: 'Andrea Denver',
      nick_name: 'Andrea',
      job: 'Bravo - Summer House, Winter House',
      price: 5000,
      availableFor24hDelivery: true,
      email: 'andreadenver@example.com',
      description: 'One-of-a-kind video for your special moments',
      password: 'password123',
      tags: ['Send a DM', 'US Talent', 'Grab your galentines'],
      categories: [1],
      avatar: 'https://www.cameo.com/cdn-cgi/image/fit=cover,format=auto,width=300,height=360/https://cdn.cameo.com/resizer/g3eI4XswV_avatar-WHMCfIxXj.jpg',
    },
    {
      name: 'Carson Kressley',
      nick_name: 'Carson',
      job: 'Bravo - Queer Eye for the Straight Guy/ RuPauls Drag Race',
      price: 7900,
      availableFor24hDelivery: true,
      email: 'carsonkressley@example.com',
      description: 'One-of-a-kind video for your special moments',
      password: 'password123',
      tags: ['Deals A$100 or Under', 'Valuable finds', 'Ofertas'],
      categories: [2],
      avatar: 'https://www.cameo.com/cdn-cgi/image/fit=cover,format=auto,width=300,height=360/https://cdn.cameo.com/resizer/TD1uJJE7-647025B2-9C4F-4BDF-9B87-43019EA3BB9F.jpg',
    },
    {
      name: 'Mrs Kasha Davis',
      nick_name: 'Kasha',
      job: "RuPaul's Drag Race Season 7 / AS8",
      price: 2500,
      availableFor24hDelivery: false,
      email: 'mrskashadavis@example.com',
      description: 'One-of-a-kind video for your special moments',
      password: 'password123',
      tags: [
        'Deals A$100 or Under',
        'Valuable finds',
        'Celebrate your sweetheart',
      ],
      categories: [2],
      avatar: 'https://www.cameo.com/cdn-cgi/image/fit=cover,format=auto,width=300,height=360/https://cdn.cameo.com/static/user/NrFTc82bL-0564ee50-4b8a-4cab-91c2-7996138e10a2.png',
    },
    {
      name: 'TJ Lavin',
      nick_name: 'TJ',
      job: "TV Host - MTV's The Challenge - BMX Rider ",
      price: 25000,
      availableFor24hDelivery: true,
      email: 'tjlavin@example.com',
      description: 'One-of-a-kind video for your special moments',
      password: 'password123',
      tags: ['Worth every penny', 'Celebrate your sweetheart', '$300 or under'],
      categories: [3],
      avatar: 'https://www.cameo.com/cdn-cgi/image/fit=cover,format=auto,width=300,height=360/https://cdn.cameo.com/resizer/Bh-shErmh_avatar-sBpSKm7B5.jpg',
    },
    {
      name: 'Tom Bergeron',
      nick_name: 'Tom',
      job: 'TV Host - AFV, Hollywood Squares, etc.',
      price: 9500,
      availableFor24hDelivery: true,
      email: 'tberj@example.com',
      description: 'One-of-a-kind video for your special moments',
      password: 'password123',
      tags: ["Mother's Day Gift", 'Dads Who Binge-Watch', "Dad's favs"],
      categories: [6],
      avatar: 'https://www.cameo.com/cdn-cgi/image/fit=cover,format=auto,width=300,height=360/https://cdn.cameo.com/static/user/ry_N6Mfam-26A35C44-FE46-468C-9854-0A795425A106.jpg',
    },
    {
      name: 'Tamra Judge',
      nick_name: 'Tamra',
      job: 'RHOC, RHUGT , The Traitors',
      price: 10000,
      availableFor24hDelivery: true,
      email: 'tamrajudge@example.com',
      description: 'One-of-a-kind video for your special moments',
      password: 'password123',
      tags: [
        'Stars supporting GLAAD',
        'Stars supporting Baby2Baby ',
        'US Talent',
      ],
      categories: [2],
      avatar: 'https://www.cameo.com/cdn-cgi/image/fit=cover,format=auto,width=300,height=360/https://cdn.cameo.com/resizer/DSsGokm18_avatar-45Fv6Ad41.jpg',
    },
    {
      name: 'Taylor Armstrong',
      nick_name: 'Taylor',
      job: 'Bravo - Real Housewives of Beverly Hills',
      price: 7500,
      availableFor24hDelivery: false,
      email: 'taylorarmstrong@example.com',
      description: 'One-of-a-kind video for your special moments',
      password: 'password123',
      tags: ['Stars supporting GLAAD', 'Promotional', 'US Talent'],
      categories: [2],
      avatar: 'https://www.cameo.com/cdn-cgi/image/fit=cover,format=auto,width=300,height=360/https://cdn.cameo.com/resizer/D2t06hxBh_avatar-xoY4jZyYj.jpg',
    },
    {
      name: 'Ross Mathews',
      nick_name: 'Ross',
      job: 'TV Host ',
      price: 9900,
      availableFor24hDelivery: true,
      email: 'helloross@example.com',
      description: 'One-of-a-kind video for your special moments',
      password: 'password123',
      tags: ['Back for more', 'Queer voices', 'Make mom laugh'],
      categories: [4],
      avatar: 'https://www.cameo.com/cdn-cgi/image/fit=cover,format=auto,width=300,height=360/https://cdn.cameo.com/resizer/eXQXkiubR_avatar-1689996772687.jpg',
    },
    {
      name: 'Roxxxy Andrews',
      nick_name: 'Roxxxy',
      job: "Reality TV - RuPaul's Drag Race",
      price: 7500,
      availableFor24hDelivery: true,
      email: 'roxxxyandrews@example.com',
      description: 'One-of-a-kind video for your special moments',
      password: 'password123',
      tags: ['Send a DM', 'Queer voices', 'US Talent'],
      categories: [2],
      avatar: 'https://www.cameo.com/cdn-cgi/image/fit=cover,format=auto,width=300,height=360/https://cdn.cameo.com/resizer/avatar-GrJZ3J9l.jpg',
    },
    {
      name: 'Chef Duff Goldman',
      nick_name: 'Duff',
      job: 'Chef - TV Personality',
      price: 5000,
      availableFor24hDelivery: true,
      email: 'duffgoldman@example.com',
      description: 'One-of-a-kind video for your special moments',
      password: 'password123',
      tags: [
        'Worth every penny',
        'Boxing Day - 24hr delivery',
        'Kick 2022 off right',
      ],
      categories: [6],
      avatar: 'https://www.cameo.com/cdn-cgi/image/fit=cover,format=auto,width=300,height=360/https://cdn.cameo.com/resizer/4YjpH4ECW_avatar-ZfKp8Ka2D.jpg',
    },
    {
      name: 'Nev Schulman',
      nick_name: 'Nev',
      job: 'MTV - Catfish',
      price: 19900,
      availableFor24hDelivery: true,
      email: 'nevschulman@example.com',
      description: 'One-of-a-kind video for your special moments',
      password: 'password123',
      tags: ['The stars have aligned', 'Roast your ex', '$300 or under'],
      categories: [2],
      avatar: 'https://www.cameo.com/cdn-cgi/image/fit=cover,format=auto,width=300,height=360/https://cdn.cameo.com/static/user/avatar-tPJbz-odP.jpg',
    },
    {
      name: 'Tammie Brown',
      nick_name: 'Tammie',
      job: "TV Star - RuPaul's Drag Race, Holiday Sparkle",
      price: 12500,
      availableFor24hDelivery: false,
      email: 'tammie@example.com',
      description: 'One-of-a-kind video for your special moments',
      password: 'password123',
      tags: ['Deals A$100 or Under', 'Ofertas', 'Celebrate your sweetheart'],
      categories: [2],
      avatar: 'https://www.cameo.com/cdn-cgi/image/fit=cover,format=auto,width=300,height=360/https://cdn.cameo.com/resizer/L8_FhJa7Y-C1E2370D-0DAE-456F-8A70-6F823F7040A5.jpg',
    },
    {
      name: 'Farrah Abraham',
      nick_name: 'Farrah',
      job: 'MTV Star - Teen Mom',
      price: 5000,
      availableFor24hDelivery: true,
      email: 'farrahabraham@example.com',
      description: 'One-of-a-kind video for your special moments',
      password: 'password123',
      tags: ['Promotional', 'Send a DM', 'Stars supporting GLAAD'],
      categories: [2],
      avatar: 'https://www.cameo.com/cdn-cgi/image/fit=cover,format=auto,width=300,height=360/https://cdn.cameo.com/resizer/TD1uJJE7-647025B2-9C4F-4BDF-9B87-43019EA3BB9F.jpg',
    },
    {
      name: 'Bethenny Frankel',
      nick_name: 'Bethenny',
      job: 'Entrepreneur - Real Housewives of New York City',
      price: 34900,
      availableFor24hDelivery: true,
      email: 'bethennyfrankel@example.com',
      description: 'One-of-a-kind video for your special moments',
      password: 'password123',
      tags: ['Say "Thank you"', 'Send a DM', 'Promotional'],
      categories: [7],
      avatar: 'https://www.cameo.com/cdn-cgi/image/fit=cover,format=auto,width=300,height=360/https://cdn.cameo.com/resizer/yKefDgZr-C_b981e007-c042-4f40-85cd-28d6b7b1d828.jpeg',
    },
    {
      name: 'Delta Work',
      nick_name: 'Delta',
      job: "Bravo - RuPaul's Drag Race",
      price: 7500,
      availableFor24hDelivery: true,
      email: 'deltawork@example.com',
      description: 'One-of-a-kind video for your special moments',
      password: 'password123',
      tags: ['Promotional', 'Send a DM', 'Queer voices'],
      categories: [2],
      avatar: 'https://www.cameo.com/cdn-cgi/image/fit=cover,format=auto,width=300,height=360/https://cdn.cameo.com/static/user/NrFTc82bL-0564ee50-4b8a-4cab-91c2-7996138e10a2.png',
    },
    {
      name: 'Dr. Jan Pol',
      nick_name: 'Jan',
      job: 'Veterinarian, Incredible Pol Farm',
      price: 15000,
      availableFor24hDelivery: false,
      email: 'thedrpol@example.com',
      description: 'One-of-a-kind video for your special moments',
      password: 'password123',
      tags: ['Dads Who Binge-Watch', 'Grandparents Day', 'US Talent'],
      categories: [2],
      avatar: 'https://www.cameo.com/cdn-cgi/image/fit=cover,format=auto,width=300,height=360/https://cdn.cameo.com/static/user/ry_N6Mfam-26A35C44-FE46-468C-9854-0A795425A106.jpg',
    },
    {
      name: 'Jenna Compono',
      nick_name: 'Jenna',
      job: 'MTV - The Challenge',
      price: 2000,
      availableFor24hDelivery: false,
      email: 'jennacompono@example.com',
      description: 'One-of-a-kind video for your special moments',
      password: 'password123',
      tags: [
        'Send a DM',
        'Stars supporting GLAAD',
        'All you need is love & Cameo',
      ],
      categories: [2],
      avatar: 'https://www.cameo.com/cdn-cgi/image/fit=cover,format=auto,width=300,height=360/https://cdn.cameo.com/resizer/Ji-P7YR5i_JamesM-170-Edit-3.jpg',
    },
    {
      name: 'Nicole Paige Brooks',
      nick_name: 'Nicole',
      job: 'Bravo - RuPaul Drag Race - Entertainer',
      price: 6900,
      availableFor24hDelivery: true,
      email: 'nicolepaigebrooks@example.com',
      description: 'One-of-a-kind video for your special moments',
      password: 'password123',
      tags: ['Stars supporting GLAAD', 'Promotional', 'US Talent'],
      categories: [2],
      avatar: 'https://www.cameo.com/cdn-cgi/image/fit=cover,format=auto,width=300,height=360/https://cdn.cameo.com/resizer/avatar-yrJ4ce8p.jpg',
    },
    {
      name: 'Riki Rachtman',
      nick_name: 'Riki',
      job: 'MTV/VH1 radio host/podcast host',
      price: 6600,
      availableFor24hDelivery: true,
      email: 'rikirachtman@example.com',
      description: 'One-of-a-kind video for your special moments',
      password: 'password123',
      tags: ['$100 or Less', 'Business', 'Reality TV Profession Boost'],
      categories: [5],
      avatar: 'https://www.cameo.com/cdn-cgi/image/fit=cover,format=auto,width=300,height=360/https://cdn.cameo.com/resizer/D2t06hxBh_avatar-xoY4jZyYj.jpg',
    },
    {
      name: 'Lady Colin Campbell',
      nick_name: 'Colin',
      job: 'Author / Reality TV',
      price: 4000,
      availableFor24hDelivery: false,
      email: 'lady_c@example.com',
      description: 'One-of-a-kind video for your special moments',
      password: 'password123',
      tags: ['British', '$50 or Less', 'Business'],
      categories: [6],
      avatar: 'https://www.cameo.com/cdn-cgi/image/fit=cover,format=auto,width=300,height=360/https://cdn.cameo.com/resizer/DSsGokm18_avatar-45Fv6Ad41.jpg',
    },
    {
      name: 'Madison Hildebrand',
      nick_name: 'Madison',
      job: 'TV Star - Million Dollar Listing LA',
      price: 2500,
      availableFor24hDelivery: false,
      email: 'madisonmalibu@example.com',
      description: 'One-of-a-kind video for your special moments',
      password: 'password123',
      tags: ['Stars supporting GLAAD', 'Promotional', 'Queer voices'],
      categories: [1],
      avatar: 'https://www.cameo.com/cdn-cgi/image/fit=cover,format=auto,width=300,height=360/https://cdn.cameo.com/static/user/avatar-SJcIHc1Rz.jpg',
    },
    {
      name: 'Cynthia Bailey',
      nick_name: 'Cynthia',
      job: 'Bravo - Real Housewives of Atlanta',
      price: 20000,
      availableFor24hDelivery: true,
      email: 'nodramacb@example.com',
      description: 'One-of-a-kind video for your special moments',
      password: 'password123',
      tags: ['Promotional', 'Send a DM', 'All you need is love & Cameo'],
      categories: [2],
      avatar: 'https://www.cameo.com/cdn-cgi/image/fit=cover,format=auto,width=300,height=360/https://cdn.cameo.com/resizer/a8mIPUEZJ-6A9AD1A1-17DF-4620-8ED3-DE0613729D49.jpg',
    },
    {
      name: 'Mike Holmes',
      nick_name: 'Mike',
      job: 'TV Producer & Host: Holmes on Homes, Holmes and Holmes & Holmes Inspection',
      price: 10000,
      availableFor24hDelivery: true,
      email: 'mholmes3679@example.com',
      description: 'One-of-a-kind video for your special moments',
      password: 'password123',
      tags: ['CA Talent', '$100 or Less', 'Request a live video call'],
      categories: [6],
      avatar: 'https://www.cameo.com/cdn-cgi/image/fit=cover,format=auto,width=300,height=360/https://cdn.cameo.com/resizer/avatar-GrJZ3J9l.jpg',
    },
    {
      name: 'Candiace Dillard Bassett',
      nick_name: 'Candiace',
      job: 'Bravo - Real Housewives of Potomac',
      price: 9900,
      availableFor24hDelivery: false,
      email: 'realcandiacedbassett@example.com',
      description: 'One-of-a-kind video for your special moments',
      password: 'password123',
      tags: ['Send a DM', 'Weddings', 'All you need is love & Cameo'],
      categories: [2],
      avatar: 'https://www.cameo.com/cdn-cgi/image/fit=cover,format=auto,width=300,height=360/https://cdn.cameo.com/resizer/L8_FhJa7Y-C1E2370D-0DAE-456F-8A70-6F823F7040A5.jpg',
    },
    {
      name: 'Simon Majumdar',
      nick_name: 'Simon',
      job: 'TV Personality - Host',
      price: 5000,
      availableFor24hDelivery: true,
      email: 'simonmajumdar@example.com',
      description: 'One-of-a-kind video for your special moments',
      password: 'password123',
      tags: ['Promotional', 'Send a DM', 'US Talent'],
      categories: [6],
      avatar: 'https://www.cameo.com/cdn-cgi/image/fit=cover,format=auto,width=300,height=360/https://cdn.cameo.com/resizer/zXFQhCwqj_avatar-We4z1zhMi.jpg',
    },
    {
      name: 'Troyzan SURVIVOR',
      nick_name: 'Troyzan',
      job: 'Survivor - Reality TV - CBS',
      price: 3900,
      availableFor24hDelivery: true,
      email: 'troyzan@example.com',
      description: 'One-of-a-kind video for your special moments',
      password: 'password123',
      tags: ['Send a DM', 'Promotional', 'US Talent'],
      categories: [2],
      avatar: 'https://www.cameo.com/cdn-cgi/image/fit=cover,format=auto,width=300,height=360/https://cdn.cameo.com/resizer/eXQXkiubR_avatar-1689996772687.jpg',
    },
    {
      name: 'Jill Zarin',
      nick_name: 'Jill',
      job: 'Bravo - Real Housewives of New York City',
      price: 9900,
      availableFor24hDelivery: true,
      email: 'mrsjillzarin@example.com',
      description: 'One-of-a-kind video for your special moments',
      password: 'password123',
      tags: ['Featured in Paid DM', 'Zoom Calls', 'Heartbreakers'],
      categories: [2],
      avatar: 'https://www.cameo.com/cdn-cgi/image/fit=cover,format=auto,width=300,height=360/https://cdn.cameo.com/resizer/D2t06hxBh_avatar-xoY4jZyYj.jpg',
    },
    {
      name: 'Chef Rachel Hargrove',
      nick_name: 'Rachel_Hargrove',
      job: 'Bravo - Below Deck',
      price: 10000,
      availableFor24hDelivery: true,
      email: 'chefrmh@example.com',
      description: 'One-of-a-kind video for your special moments',
      password: 'password123',
      tags: ['Hello Summer', 'US Talent', 'Kick 2022 off right'],
      categories: [6],
      avatar: 'https://www.cameo.com/cdn-cgi/image/fit=cover,format=auto,width=300,height=360/https://cdn.cameo.com/resizer/eXQXkiubR_avatar-1689996772687.jpg',
    },
    {
      name: 'Phaedra Parks',
      nick_name: 'Phaedra',
      job: 'Bravo - The Real Housewives of Atlanta',
      price: 19500,
      availableFor24hDelivery: true,
      email: 'phaedraparks@example.com',
      description: 'One-of-a-kind video for your special moments',
      password: 'password123',
      tags: [
        'Featured in Paid DM',
        'Get a graduation speech',
        'Stars supporting GLAAD',
      ],
      categories: [2],
      avatar: 'https://www.cameo.com/cdn-cgi/image/fit=cover,format=auto,width=300,height=360/https://cdn.cameo.com/resizer/jxs3vIV2m_avatar-eGBZojZ46.jpg',
    },
    {
      name: 'Heather Thomson',
      nick_name: 'Heather',
      job: 'Real Housewives of New York City',
      price: 10000,
      availableFor24hDelivery: true,
      email: 'heatherthomson@example.com',
      description: 'One-of-a-kind video for your special moments',
      password: 'password123',
      tags: ['Send a DM', 'US Talent', '$100 or Less'],
      categories: [2],
      avatar: 'https://www.cameo.com/cdn-cgi/image/fit=cover,format=auto,width=300,height=360/https://cdn.cameo.com/resizer/cRPMJUf-7_avatar-pRJvnDAg8.jpg',
    },
    {
      name: 'Rachel Reilly',
      nick_name: 'Rachel_Reilly',
      job: 'Reality TV Star - Big Brother, Amazing Race, Fear Factor',
      price: 3500,
      availableFor24hDelivery: true,
      email: 'rachel.reilly@example.com',
      description: 'One-of-a-kind video for your special moments',
      password: 'password123',
      tags: [
        'Send a DM',
        'All you need is love & Cameo',
        '24hr Delivery - $100 or Less',
      ],
      categories: [2],
      avatar: 'https://www.cameo.com/cdn-cgi/image/fit=cover,format=auto,width=300,height=360/https://cdn.cameo.com/resizer/avatar-yrJ4ce8p.jpg',
    },
    {
      name: 'Whitney Mixter',
      nick_name: 'Whitney',
      job: 'Reality TV Star',
      price: 5500,
      availableFor24hDelivery: true,
      email: 'whitneymixter@example.com',
      description: 'One-of-a-kind video for your special moments',
      password: 'password123',
      tags: ['Send a DM', 'Queer voices', 'US Talent'],
      categories: [2],
      avatar: 'https://www.cameo.com/cdn-cgi/image/fit=cover,format=auto,width=300,height=360/https://cdn.cameo.com/resizer/_a7Cp_zBW_avatar-vIEHzJwHW.jpg',
    },
    {
      name: 'Lyndsay & Leslie HGTV Unsellable Houses',
      nick_name: 'Lyndsay',
      job: 'HGTV - Unsellable Houses',
      price: 25000,
      availableFor24hDelivery: false,
      email: 'lyndsayandleslie@example.com',
      description: 'One-of-a-kind video for your special moments',
      password: 'password123',
      tags: ['Reality TV Profession Boost', 'Cyber Monday 2023', 'Send a DM'],
      categories: [2],
      avatar: 'https://www.cameo.com/cdn-cgi/image/fit=cover,format=auto,width=300,height=360/https://cdn.cameo.com/resizer/a8mIPUEZJ-6A9AD1A1-17DF-4620-8ED3-DE0613729D49.jpg',
    },
    {
      name: 'Michael Chakraverty',
      nick_name: 'Michael',
      job: 'Reality TV - Great British Baking Show',
      price: 3000,
      availableFor24hDelivery: true,
      email: 'mschakraverty@example.com',
      description: 'One-of-a-kind video for your special moments',
      password: 'password123',
      tags: ['UK Father’s Day', 'British', 'Stars supporting GLAAD'],
      categories: [2],
      avatar: 'https://www.cameo.com/cdn-cgi/image/fit=cover,format=auto,width=300,height=360/https://cdn.cameo.com/resizer/4YjpH4ECW_avatar-ZfKp8Ka2D.jpg',
    },
    {
      name: 'Chris Harrison',
      nick_name: 'Chris',
      job: "TV Host - ABC's The Bachelor",
      price: 27500,
      availableFor24hDelivery: true,
      email: 'chrisbharrison@example.com',
      description: 'One-of-a-kind video for your special moments',
      password: 'password123',
      tags: ['Promotional', 'Stars supporting GLAAD', 'Here’s to another year'],
      categories: [2],
      avatar: 'https://www.cameo.com/cdn-cgi/image/fit=cover,format=auto,width=300,height=360/https://cdn.cameo.com/resizer/eXQXkiubR_avatar-1689996772687.jpg',
    },
    {
      name: 'Carlos King',
      nick_name: 'Carlos',
      job: 'Podcast Host - Reality with the King',
      price: 7500,
      availableFor24hDelivery: false,
      email: 'cking1079@example.com',
      description: 'One-of-a-kind video for your special moments',
      password: 'password123',
      tags: [
        '$100 or Less',
        'Reality TV Profession Boost',
        'Cyber Monday 2023',
      ],
      categories: [6],
      avatar: 'https://www.cameo.com/cdn-cgi/image/fit=cover,format=auto,width=300,height=360/https://cdn.cameo.com/resizer/ameozFf-Z_avatar-1677196331157.jpg',
    },
    {
      name: 'Buddha Lo',
      nick_name: 'Buddha',
      job: 'Bravo- Top Chef',
      price: 10000,
      availableFor24hDelivery: false,
      email: 'buddhalo@example.com',
      description: 'One-of-a-kind video for your special moments',
      password: 'password123',
      tags: ['Business', 'Reality TV Profession Boost', 'Cyber Monday 2023'],
      categories: [2],
      avatar: 'https://www.cameo.com/cdn-cgi/image/fit=cover,format=auto,width=300,height=360/https://cdn.cameo.com/resizer/a8mIPUEZJ-6A9AD1A1-17DF-4620-8ED3-DE0613729D49.jpg',
    },
    {
      name: 'Jim Shockey',
      nick_name: 'Jim',
      job: 'TV Host - The Outdoor Channel',
      price: 5000,
      availableFor24hDelivery: true,
      email: 'jimshockey@example.com',
      description: 'One-of-a-kind video for your special moments',
      password: 'password123',
      tags: ['Send a DM', 'CA Talent', '$50 or Less'],
      categories: [3],
      avatar: 'https://www.cameo.com/cdn-cgi/image/fit=cover,format=auto,width=300,height=360/https://cdn.cameo.com/resizer/dDURo5LfcL_avatar-1720408367449.jpg',
    },
    {
      name: 'Ana Quincoces',
      nick_name: 'Ana',
      job: 'Real Housewives of Miami',
      price: 4500,
      availableFor24hDelivery: true,
      email: 'anaqooks@example.com',
      description: 'One-of-a-kind video for your special moments',
      password: 'password123',
      tags: ['US Talent', '$50 or Less', 'Reality TV Profession Boost'],
      categories: [2],
      avatar: 'https://www.cameo.com/cdn-cgi/image/fit=cover,format=auto,width=300,height=360/https://cdn.cameo.com/resizer/ameozFf-Z_avatar-1677196331157.jpg',
    },
    {
      name: 'Dr. Jan And Diane Pol',
      nick_name: 'Jan_Pol',
      job: 'TV Stars - The Incredible Dr. Pol',
      price: 20000,
      availableFor24hDelivery: false,
      email: 'drjananddianepol@example.com',
      description: 'One-of-a-kind video for your special moments',
      password: 'password123',
      tags: ['US Talent', 'Reality TV Profession Boost', 'Cyber Monday 2023'],
      categories: [2],
      avatar: 'https://www.cameo.com/cdn-cgi/image/fit=cover,format=auto,width=300,height=360/https://cdn.cameo.com/resizer/dDURo5LfcL_avatar-1720408367449.jpg',
    },
    {
      name: 'Joyce Giraud',
      nick_name: 'Joyce',
      job: 'Actress/Miss Puerto Rico/Housewives',
      price: 4900,
      availableFor24hDelivery: true,
      email: 'joycegiraud@example.com',
      description: 'One-of-a-kind video for your special moments',
      password: 'password123',
      tags: ['US Talent', '$50 or Less', 'Request a live video call'],
      categories: [1],
      avatar: 'https://www.cameo.com/cdn-cgi/image/fit=cover,format=auto,width=300,height=360/https://cdn.cameo.com/resizer/D2t06hxBh_avatar-xoY4jZyYj.jpg',
    },
    {
      name: 'Barbara Weber',
      nick_name: 'Barbara',
      job: 'Reality TV - The Bachelor',
      price: 5900,
      availableFor24hDelivery: true,
      email: 'barbaraweber@example.com',
      description: 'One-of-a-kind video for your special moments',
      password: 'password123',
      tags: ['Send a DM', 'Stars supporting GLAAD', 'Promotional'],
      categories: [2],
      avatar: 'https://www.cameo.com/cdn-cgi/image/fit=cover,format=auto,width=300,height=360/https://cdn.cameo.com/resizer/4YjpH4ECW_avatar-ZfKp8Ka2D.jpg',
    },
  ];

  for (const talentData of talents) {
    const existing = await talentRepository.findOneBy({
      email: talentData.email,
    });
    const categories = await categoryRepository.find({
      where: { id: In(talentData.categories || []) },
    });
    const role = await roleRepository.findOneBy({ name: 'talent' });
    if (!existing && categories.length > 0) {
      const bcrypt = require('bcrypt');
      const password = await bcrypt.hash(talentData.password, 10);
      const talent = await talentRepository.create({
        ...talentData,
        password,
        categories,
        roles: [role],
      });
      talent.categories = categories;
      await talentRepository.save(talent);
    }
  }
};
